### ISSUE TITLE
Text generated is "too long" 

### ISSUE THREAD

**Issue by Trevoke** [One-com/react-truncate#4]
Here is a screenshot of what I mean - you can see that on the original load, using a mobile device tool on Chrome, the text goes too far. (it should be aligned, to the left and to the right, with the blue bar underneath).

![screenshot from 2016-06-15 09-35-57](https://cloud.githubusercontent.com/assets/67913/16081694/9a241684-32dc-11e6-9be2-ad7ed14ba57c.png)

Fun fact, if I turn off the mobile device tool and then turn it on again, this happens:

![screenshot from 2016-06-15 09-37-49](https://cloud.githubusercontent.com/assets/67913/16081764/e0c9caf2-32dc-11e6-99cc-4421da31e1a0.png)

![screenshot from 2016-06-15 09-37-59](https://cloud.githubusercontent.com/assets/67913/16081767/e4570be4-32dc-11e6-9423-d85666a8724b.png)

So the code is doing the right thing, mostly. Let me know if you need more stuff from me.

**Comment by PabloSichert** [comment]
Thank you for the screenshots - from your description I assume that re-sizing the window (without toggling chrome device mode) also results in re-rendering and correctly truncating the text, is that correct?

It would be helpful to know which children you provided to the component. Does the child re-render while `<Truncate>` has been mounted already, for example by fetching its text-content asynchronously?

Was there any error in the console?

**Comment by Trevoke** [comment]
There were no errors in the console, and no children were passed to the component, just jsx-interpolated text ( `props.foo` )

If I don't toggle chrome device mode, then resizing the window won't do anything, since it's set to the mobile width -- and my use case is mobile devices, so I didn't try on a regular browser window.

**Comment by Trevoke** [comment]
I have moved on to another module, react-ellipsify, that provided the desired behavior along with the text-expansion feature I desired, so my available time to help you troubleshoot has unfortunately been cut short for the time being.

**Comment by PabloSichert** [comment]
Having revealed this bug is helpful anyway - so thanks for the contribution :sun_with_face: 

I have found an explanation for the observed behavior:
- Pages that are not optimized for mobile get enhanced with an "text inflating algorithm" aka "font boosting", if not prevented
- Chrome Device Mode emulates rendering on a mobile device and triggers said behavior

> [...] When pages load, Font Boosting increases the font size of text in wide columns, so you won't have to zoom in on them as much and hence every column fits onscreen at a legible text size. - [WebKit Bug Tracker](https://bugs.webkit.org/show_bug.cgi?id=FontBoosting)

Why is this causing trouble with react-truncate?
- The calculations inside this module are based on font properties read by `.getComputedStyle()`. Unfortunately those numbers lie when font boosting is applied and return the initial font sizes
- That explains why the text in your screenshot is cut to the correct line of numbers, but exceeds the boundaries on the right side

How can you fix it?
- Solution: Be explicit to the browser about rendering on mobile and add  `<meta name="viewport" content="width=device-width, initial-scale=1">` to the document head - [source](http://stackoverflow.com/a/14131893)
- Hack: Apply `max-height: 999999px;` CSS property to text elements to disable font boosting - [source](http://stackoverflow.com/a/12965146) Note: this works when you run it on an actual mobile device - the chrome emulation will still apply font boosting
- Use not widely adopted properties: `text-size-adjust` in [Safari](https://developer.apple.com/library/ios/documentation/AppleApplications/Reference/SafariWebContent/AdjustingtheTextSize/AdjustingtheTextSize.html#//apple_ref/doc/uid/TP40006510-SW16) and on [MDN](https://developer.mozilla.org/en-US/docs/Web/CSS/text-size-adjust)

--

A note on the text-expansion: This is something that you could easily implement using react-truncate. In the link you provide to `ellipsis` you could toggle a variable in your parent component and provide it to the `lines` prop, 0 means the text will not be truncated

**Comment by PabloSichert** [comment]
Here you have a [gist](https://gist.github.com/PabloSichert/ca3e7cda3bccdcc3fd7b3983f07c777d) for an example `<ReadMore>` component that wraps `<Truncate>`
