### ISSUE TITLE
Property to refresh/recalculate targetWidth

### ISSUE THREAD

**Issue by gamtiq** [One-com/react-truncate#49]
In some cases it is necessary to re-render a truncate component although its existent props (children, ellipsis and lines) are not modified. For example, when size of a parent DOM-element (component) is changed without window resizing.
Now I use the following workaround to re-render the truncate component when necessary: `this.truncateRef.onResize();`
But it would be useful to have special property which will trigger recalculation of `targetWidth`.

**Comment by PabloSichert** [comment]
Your solution looks good enough to me, I don't think it justifies another property.

If you have strong feelings about this and want to implement that feature I'd accept a PR.

**Comment by bongione** [comment]
I didn't see this issue until after I had created such a property. 
The rationale for having a separate property instead of using the ref is that I can keep all the DOM manipulation within the component, and as a client use it declaratively.

I called the property width, and it simply forces a recalculate size after update if the width property changed. I will create a PR for it.

**Comment by PabloSichert** [comment]
You can now control the target size by changing the `width` property. It's out on npm with [`2.4.0`](https://github.com/One-com/react-truncate/releases/tag/v2.4.0).

Thank you for your contribution!
